title: Traveller tips website!
email: info@travellertips.me
description: > # this means to ignore newlines until "baseurl:"
  Travellertips website is a great source with special hints and tips for travellers. We gather useful information about the place, how to get there and what budget you should count on.
  We try to collect the most interesting places and share this information with you, dear wonderer. In some places we hide a treasure for you, go and check it! If you want to find the most interesting and 
  sometimes hidden places around the Globe then this website is a great starting point!
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://travellertips.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: travellertipsme

# Build settings

plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-paginate
  
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      
environment: production

paginate: 6
paginate_path: "/blog/page:num/"

assets:
  source_maps: false # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: true
  gzip: true
  defaults:
    js: { integrity: true } # true on JEKYLL_ENV=production
    css: { integrity: true } # true on JEKYLL_ENV=production
    img: { integrity: true } # true on JEKYLL_ENV=production
  caching:
    path: ".jekyll-cache/assets"
    type: file # Possible values: memory, file
    enabled: true
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/images/general
    - _assets/images/posts
    - _assets/images/thumbnails650
    - _assets/images/thumbnails320
    - _assets/images/maps
    - _assets/css
    - _assets/js
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - README.md

ga_analytics: UA-103038704-1

name: travellertips

permalink: pretty

